version: "3.9"
services:
  web:
    build: .
    command:
      [
        sh,
        -c,
        "cd /app && npm run build && npm run start-production"
      ]
    ports:
      - "8000:8000"
    links:
      - pg_db
    volumes:
      - .:/app
  pg_db:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5C#z975DmJ6!MF#9k@GD
      - POSTGRES_DB=QueChall
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
